# Generated by Django 5.2 on 2025-10-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('bid', models.CharField(max_length=255)),
                ('img', models.URLField()),
            ],
            options={
                'db_table': 'userinfo',
                'managed': False,
            },
        ),
    ]
