# Generated by Django 5.2.1 on 2025-05-14 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'managed': False},
        ),
    ]
