# Generated by Django 5.2.1 on 2025-05-14 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_user', '0002_alter_userinfo_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userinfo',
            table='user_info',
        ),
    ]
