# Generated by Django 5.2 on 2025-07-02 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_vendor_history_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor_history',
            options={'managed': True},
        ),
    ]
