# Generated by Django 5.2.1 on 2025-05-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_userinfo_options_userinfo_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.IntegerField()),
                ('event_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'l2_vendor_history',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='activation_status',
            field=models.CharField(default='pending'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.BinaryField(),
        ),
        migrations.AlterModelTable(
            name='userinfo',
            table='market_userinfo',
        ),
    ]
