# Generated by Django 5.2.1 on 2025-05-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_vendor_history_userinfo_activation_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendor_history',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='img',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
