# Generated by Django 5.2 on 2025-05-08 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password', models.TextField()),
                ('info', models.TextField(blank=True, null=True)),
                ('bid', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
