# Generated by Django 5.2 on 2025-05-18 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('organization_id', models.IntegerField()),
                ('title', models.CharField(max_length=256)),
                ('audit_type', models.CharField(choices=[('INT', 'Internal'), ('EXT', 'External'), ('COM', 'Compliance')], default='INT', max_length=3)),
                ('status', models.CharField(choices=[('PLN', 'Planned'), ('INP', 'In Progress'), ('CMP', 'Completed')], default='PLN', max_length=3)),
                ('scheduled_date', models.DateField()),
                ('created_by', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Logistics',
            fields=[
                ('entity_id', models.AutoField(primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('WAR', 'Warehousing'), ('VEH', 'Vehicle'), ('SUP', 'Supplier')], max_length=3)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule_start', models.DateField()),
                ('schedule_end', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('time_zone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('SCHED', 'Scheduled'), ('RESCH', 'Rescheduled'), ('CNCLD', 'Cancelled'), ('CMPLT', 'Completed')], default='SCHED', max_length=5)),
                ('notes', models.TextField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now_add=True)),
                ('audit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='audit_management.audit')),
            ],
        ),
    ]
