# Generated by Django 5.2 on 2025-05-18 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
