# Generated by Django 5.2 on 2025-05-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_management', '0002_alter_scheduling_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
